-- Supabase Dashboard > SQL Editor에서 실행하세요.
-- owner_id는 이후 소유자 연결을 위한 nullable UUID 칸이며 auth.users FK는 없습니다.
-- RLS 정책과 anon/authenticated 권한을 추가하지 않아 이 역할들은 자료를 읽을 수 없습니다.

begin;

create table if not exists public.learning_notes (
  id bigint generated by default as identity primary key,
  owner_id uuid,
  title text not null,
  content text not null,
  created_at timestamptz not null default now(),
  constraint learning_notes_title_content_key unique (title, content)
);

alter table public.learning_notes enable row level security;

-- 기존에 부여된 권한이 있더라도 공개/로그인 사용자에게 자료를 열지 않습니다.
revoke all privileges on table public.learning_notes from public, anon, authenticated;

insert into public.learning_notes (owner_id, title, content)
values
  (null, '과제', '실습용 가상 과제 기록'),
  (null, '포트폴리오', '실습용 가상 포트폴리오 기록'),
  (null, '아침 리추얼', '실습용 가상 리추얼 기록'),
  (null, '훈련 행정 자료', '실습용 가상 행정 기록')
on conflict (title, content) do nothing;

commit;
